### ISSUE TITLE
question: Is plugin prepared for LogAnalytics data limit?

### ISSUE THREAD

**Issue by marcosflobo** [yokawasa/fluent-plugin-azure-loganalytics#15]
Hello,

This is not an issue, just a question.

LogAnalytics API has a limit (I think it's 32MBytes) of data per request. Is this plugin ready to not overpass that limit?

Thanks!

**Comment by yokawasa** [comment]
@marcosflobo 
Very sorry for the late response. Unfortunately the plugin isn't ready for not overpassing the limit. I added this to the backlog. Please check an update on #16 if you want the feature.
