### ISSUE TITLE
time filed added as string

### ISSUE THREAD

**Issue by floriankoch** [yokawasa/fluent-plugin-azure-loganalytics#19]
If i add an timefield to the output 

```
add_time_field true
time_field_name xtime
time_format %Y%m%d-%H:%M:%S
localtime true
```

its added as string in LogAnalytics, how can i change this to type timestamp?

**Comment by yokawasa** [comment]
@floriankoch 

Can you try the following time format?

```
add_time_field true
time_field_name xtime
time_format %FT%T%z
localtime true
```

**Comment by yokawasa** [comment]
@floriankoch 
if you give time field with the ISO 8601 format YYYY-MM-DDThh:mm:ssZ, it'll be ingested as timestamp type.
Please try this
```
time_format %FT%T%z
```

I'm closing the issue. Please open another issue if you have any problems

**Comment by floriankoch** [comment]
@yokawasa   yes this works, thank you
