### ISSUE TITLE
Question: Enable debug logging

### ISSUE THREAD

**Issue by marcosflobo** [yokawasa/fluent-plugin-azure-loganalytics#20]
Hello,

This is more of a question than an issue. I would like to know how to enable the DEBUG level logging in this plugin

In the fluentd.conf file, at root level, I've put
```
<system>
    log_level debug
    workers 4
</system>
...
``` 
And I can see the DEBUG for the output plugins like the HTTP one, but nothing for the fluent-plugin-azure-loganalytics type.

Would you be able to give me a hit about this?

Thanks!

**Comment by yokawasa** [comment]
@marcosflobo very sorry for the slow response.
fluent-plugin-azure-loganalytics doesn't output any logging info except fatal one. 
- https://github.com/yokawasa/fluent-plugin-azure-loganalytics/blob/master/lib/fluent/plugin/out_azure-loganalytics.rb#L100-L101

Please let me know what kind of information you want the plugin to output?

**Comment by marcosflobo** [comment]
@yokawasa no worries ;)

We had a production issue missing packages and we suspected about your plugin. At the it was not your plugin and we solved the issue.

Thank you for your work on this plugin, it's helping us a lot!

**Comment by yokawasa** [comment]
@marcosflobo thank you. Now I'm closing the issue but feel free to open an issue if you have any feedback / request on the plugin.
