### ISSUE TITLE
Does this plugin support json format log_type jsonABT

### ISSUE THREAD

**Issue by parthivjoshi** [yokawasa/fluent-plugin-azure-loganalytics#6]
I am trying to forward k8 logs to azure log analytics with following settings and it's not working.  Can you help?

<source>
    @type tail                         # input plugin
    path /tmp/access.log   # monitoring file
    pos_file /tmp/fluentd_pos_file     # position file
    format json                      # format
    tag azure-loganalytics.access      # tag
</source>

<match azure-loganalytics.**>
    @type azure-loganalytics
    customer_id foobar   # Customer ID aka WorkspaceID String
    shared_key foobar     # The primary or the secondary Connected Sources client authentication key
    log_type jsonON  # The name of the event type. ex) ApacheAccessLog
    add_tag_field true
    tag_field_name json_ON_tag
</match>

**Comment by yokawasa** [comment]
@parthivjoshi 
Looks like `@type tail` in fluentd support `JSON` format. The following is fluentd's tail plugin's doc:
- https://docs.fluentd.org/v0.10/articles/in_tail 

Also I found an example of reading JSON data and push them into elasticsearch. This is not for log analytics but might help you to understand how you configure tail plugin in reading JSON data.
- https://docs.fluentd.org/v0.12/articles/recipe-json-to-elasticsearch

One more example is this (reading CSV data and push them into log analytics):
- https://github.com/yokawasa/fluent-plugin-azure-loganalytics/blob/master/examples/fluent_csv.conf

Hope this would help

**Comment by yokawasa** [comment]
@parthivjoshi I'm closing the issue but please feel free to re-open if you need further discussions. thanks
