### ISSUE TITLE
Support Azure sovereign cloud

### ISSUE THREAD

**Issue by catweisun** [yokawasa/fluent-plugin-azure-loganalytics#7]
Azure sovereign cloud is using different endpoints for data collector api, such as https://<CustomerId>.ods.opinsights.azure.cn/api/logs?api-version=2016-04-01 for Azure China, it's better to support customized endpoint for sovereign cloud environment.

Thanks.

**Comment by yokawasa** [comment]
Resolved thanks to your contribution : PR #8
